### PR TITLE
Support subresource integrity on imported scripts

### PR DESCRIPTION
**Pull request by cornwe19**

### CODE REVIEW

**Comment by cornwe19** [comment]
@EPNW-Eric Not sure if you're open to contributions, but I'm looking to make it possible to enforce [subresource integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) on scripts injected by this library

**Comment by EPNW-Eric** [comment]
I will look into it 👍

**Comment by Eric-Prokop** [comment]
Quick question @cornwe19: Do you agree with the terms of the LICENSE (Apache 2.0) and agree that your codechanges are published under it?

https://github.com/EP-u-NW/inject_js/blob/ec83dde6dcdb7c401ee4bafc3dc1f3b8941357c5/LICENSE#L191

**Comment by cornwe19** [comment]
> Quick question @cornwe19: Do you agree with the terms of the LICENSE (Apache 2.0) and agree that your codechanges are published under it?
> 
> https://github.com/EP-u-NW/inject_js/blob/ec83dde6dcdb7c401ee4bafc3dc1f3b8941357c5/LICENSE#L191

Yep, agreed

**Comment by Eric-Prokop** [comment]
Published :) !

**Pull request merged**
